trigger:
  branches:
    include:
      - main
pool:
  name: 'Default'

jobs:
- job: DeployNM
  displayName: 'Deploy Cassandra'
  steps:

    - task: AzureCLI@2
      displayName: 'Deploy anm with Bicep'
      inputs:
        azureSubscription: 'axwaymanishdepops1'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Define parameters TEST
          $resourceGroupName = 'RG-mavishnoi'
          $location = 'westeurope'
          $initialCassandraAdminPassword = 'Test123'
          $cassandraVersion = '4.0'
          $subscriptionID = '9436480f-c708-4e0f-aba3-3d5af128e84a'
          $vnetID = 'Test12345'
          $subnetName= 'Test12345'
          $delegatedManagementSubnetId='/subscriptions/9436480f-c708-4e0f-aba3-3d5af128e84a/resourceGroups/RG-mavishnoi/providers/Microsoft.Network/virtualNetworks/Test12345/subnets/Test12345'
          az account set -s $subscriptionID
          az network vnet create -n $vnetID -l $location -g $resourceGroupName --subnet-name $subnetName
          #az role assignment create --assignee a232010e-820c-4083-83bb-3ace5fc29d0b --role 4d97b98b-1d4f-4787-a291-c67834d212e7 --scope /subscriptions/$subscriptionID/resourceGroups/$resourceGroupName/providers/Microsoft.Network/virtualNetworks/$vnetID
          az managed-cassandra cluster create --cluster-name TEST1234 --resource-group $resourceGroupName --location $location --delegated-management-subnet-id $delegatedManagementSubnetId --initial-cassandra-admin-password $initialCassandraAdminPassword --cassandra-version $cassandraVersion --debug
      
